import React, { useState } from 'react';
import { useRestaurant } from '../../context/RestaurantContext';
import { Reservation } from '../../types';
import { CalendarDays, Plus, CheckCircle2, XCircle } from 'lucide-react';

export const ReservationsView: React.FC = () => {
  const { reservations, saveReservation, updateReservationStatus, tables, customers } = useRestaurant();
  const [editing, setEditing] = useState<Reservation | null>(null);
  const empty: Reservation = { id:'', clienteNome:'', telefone:'', dataHora:new Date(Date.now()+3600000).toISOString().slice(0,16), pessoas:2, status:'reservada', observacao:'', criadoPor:'Administrador' };
  const save = () => { if (!editing?.clienteNome.trim()) return; saveReservation({...editing,id:editing.id||`res-${Date.now()}`,criadoPor:editing.criadoPor||'Administrador'}); setEditing(null); };
  return <div className="max-w-7xl mx-auto px-4 sm:px-6 py-6 space-y-5"><div className="flex justify-between items-center"><div><h2 className="text-xl font-bold font-serif flex items-center gap-2"><CalendarDays className="w-6 h-6 text-blue-600"/>Reservas</h2><p className="text-xs text-stone-500">Reserve mesas sem criar pedido antecipadamente.</p></div><button onClick={()=>setEditing(empty)} className="px-4 py-2 bg-blue-600 text-white rounded-xl text-xs font-bold flex gap-1.5"><Plus className="w-4 h-4"/>Nova reserva</button></div>
  <div className="grid gap-3">{reservations.sort((a,b)=>a.dataHora.localeCompare(b.dataHora)).map(r=><div key={r.id} className="bg-white border border-stone-200 rounded-2xl p-4 flex flex-col md:flex-row md:items-center justify-between gap-3"><div><div className="font-bold">{r.clienteNome} • {r.pessoas} pessoas</div><div className="text-xs text-stone-500">{new Date(r.dataHora).toLocaleString('pt-BR')} • Mesa {r.mesaNumero || 'a definir'} • {r.telefone || 'sem telefone'}</div>{r.observacao&&<div className="text-xs text-stone-400 mt-1">{r.observacao}</div>}</div><div className="flex gap-2 items-center"><span className="px-2 py-1 rounded-lg bg-stone-100 text-[10px] font-bold uppercase">{r.status}</span>{!['cancelada','finalizada'].includes(r.status)&&<><button onClick={()=>updateReservationStatus(r.id,'confirmada')} className="px-2 py-1 text-emerald-700 text-xs font-bold"><CheckCircle2 className="w-4 h-4 inline mr-1"/>Confirmar</button><button onClick={()=>updateReservationStatus(r.id,'cancelada')} className="px-2 py-1 text-rose-600 text-xs font-bold"><XCircle className="w-4 h-4 inline mr-1"/>Cancelar</button></>}</div></div>)}{!reservations.length&&<div className="bg-white border border-dashed border-stone-300 rounded-2xl p-10 text-center text-stone-400">Nenhuma reserva.</div>}</div>
  {editing&&<div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4"><div className="bg-white rounded-2xl p-6 w-full max-w-lg space-y-3"><h3 className="font-bold text-lg">Nova reserva</h3><input value={editing.clienteNome} onChange={e=>setEditing({...editing,clienteNome:e.target.value})} placeholder="Nome" className="w-full p-2.5 border rounded-xl"/><input value={editing.telefone||''} onChange={e=>setEditing({...editing,telefone:e.target.value})} placeholder="Telefone" className="w-full p-2.5 border rounded-xl"/><input type="datetime-local" value={editing.dataHora} onChange={e=>setEditing({...editing,dataHora:e.target.value})} className="w-full p-2.5 border rounded-xl"/><div className="grid grid-cols-2 gap-2"><input type="number" min="1" value={editing.pessoas} onChange={e=>setEditing({...editing,pessoas:Number(e.target.value)})} placeholder="Pessoas" className="p-2.5 border rounded-xl"/><select value={editing.mesaNumero||''} onChange={e=>setEditing({...editing,mesaNumero:e.target.value?Number(e.target.value):undefined})} className="p-2.5 border rounded-xl"><option value="">Mesa automática</option>{tables.filter(t=>t.status==='livre'||t.status==='reservada').map(t=><option key={t.numero} value={t.numero}>Mesa {t.numero}</option>)}</select></div><input value={editing.observacao||''} onChange={e=>setEditing({...editing,observacao:e.target.value})} placeholder="Observação" className="w-full p-2.5 border rounded-xl"/><div className="flex justify-end gap-2"><button onClick={()=>setEditing(null)} className="px-4 py-2 bg-stone-100 rounded-xl text-xs font-bold">Cancelar</button><button onClick={save} className="px-4 py-2 bg-blue-600 text-white rounded-xl text-xs font-bold">Salvar</button></div></div></div>}
  </div>;
};
